"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import glob

APP = ['file merger start program.pyw']
DATA_FILES = [('packages', glob.glob('packages/*.*')), ('resources', glob.glob('resources/*.*'))]
OPTIONS = {'argv_emulation': True, 'iconfile':'resources/icon.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
